#include <stdio.h>

int	main()
{
	int		a, b, e;
	char	c;
	char	*str = "string";

	a = 12;
	b = -3;
	c = 'M';
	e = 13;

//	printf("This is test  0: |%#x|---|%5s|\n", 42, "%x");
//	printf("This is test  2: |%#X|---|%5s|\n", 42, "%X");

	printf("STANDART TYPE d (i):\nnumber > 0\n");
	printf("This is test  0: |%3.*d|---|%5s|\n", e, a, "%3.*d");
	printf("This is test  1: |%+3.*d|---|%5s|\n", e, a, "%+3.*d");
	printf("This is test  2: |%-3.*d|---|%5s|\n", e, a, "%-3.*d");
	printf("This is test  3: |% 3.*d|---|%5s|\n", e, a, "% 3.*d");
	printf("This is test  4: |%03.*d|---|%5s|\n", e, a, "%03.*d");
	printf("This is test  5: |% +3.*d|---|%5s|\n", e, a, "% +3.*d");
	printf("This is test  6: |% -3.*d|---|%5s|\n", e, a, "% -3.*d");
	printf("This is test  7: |%+-3.*d|---|%5s|\n", e, a, "%+-3.*d");
	printf("This is test  8: |%0-3.*d|---|%5s|\n", e, a, "%0-3.*d");
	printf("This is test  9: |%0+3.*d|---|%5s|\n", e, a, "%0+3.*d");
	printf("This is test 10: |% 03.*d|---|%5s|\n", e, a, "% 03.*d");
	printf("This is test 11: |% -3.*d|---|%5s|\n\n", e, a, "% -3.*d");

	printf("number < 0\n");
	printf("This is test  0: |%3.*d|---|%5s|\n", e, b, "%3.*d");
	printf("This is test  1: |%+3.*d|---|%5s|\n", e, b, "%+3.*d");
	printf("This is test  2: |%-3.*d|---|%5s|\n", e, b, "%-3.*d");
	printf("This is test  3: |% 3.*d|---|%5s|\n", e, b, "% 3.*d");
	printf("This is test  4: |%03.*d|---|%5s|\n", e, b, "%03.*d");
	printf("This is test  5: |% +3.*d|---|%5s|\n", e, b, "% +3.*d");
	printf("This is test  6: |% -3.*d|---|%5s|\n", e, b, "% -3.*d");
	printf("This is test  7: |%+-3.*d|---|%5s|\n", e, b, "%+-3.*d");
	printf("This is test  8: |%0-3.*d|---|%5s|\n", e, b, "%0-3.*d");
	printf("This is test  9: |%0+3.*d|---|%5s|\n", e, b, "%0+3.*d");
	printf("This is test 10: |% 03.*d|---|%5s|\n", e, b, "% 03.*d");
	printf("This is test 11: |% -3.*d|---|%5s|\n\n", e, b, "% -3.*d");

	printf("STANDART TYPE u:\nnumber > 0\n");
	printf("This is test  0: |%3.*u|---|%5s|\n", e, a, "%3.*u");
	printf("This is test  1: |%+3.*u|---|%5s|\n", e, a, "%+3.*u");
	printf("This is test  2: |%-3.*u|---|%5s|\n", e, a, "%-3.*u");
	printf("This is test  3: |% 3.*u|---|%5s|\n", e, a, "% 3.*u");
	printf("This is test  4: |%03.*u|---|%5s|\n", e, a, "%03.*u");
	printf("This is test  5: |% +3.*u|---|%5s|\n", e, a, "% +3.*u");
	printf("This is test  6: |% -3.*u|---|%5s|\n", e, a, "% -3.*u");
	printf("This is test  7: |%+-3.*u|---|%5s|\n", e, a, "%+-3.*u");
	printf("This is test  8: |%0-3.*u|---|%5s|\n", e, a, "%0-3.*u");
	printf("This is test  9: |%0+3.*u|---|%5s|\n", e, a, "%0+3.*u");
	printf("This is test 10: |% 03.*u|---|%5s|\n", e, a, "% 03.*u");
	printf("This is test 11: |% -3.*u|---|%5s|\n\n", e, a, "% -3.*u");

	printf("number < 0\n");
	printf("This is test  1: |%3.*u|---|%5s|\n", e, b, "%3.*u");
	printf("This is test  1: |%+3.*u|---|%5s|\n", e, b, "%+3.*u");
	printf("This is test  2: |%-3.*u|---|%5s|\n", e, b, "%-3.*u");
	printf("This is test  3: |% 3.*u|---|%5s|\n", e, b, "% 3.*u");
	printf("This is test  4: |%03.*u|---|%5s|\n", e, b, "%03.*u");
	printf("This is test  5: |% +3.*u|---|%5s|\n", e, b, "% +3.*u");
	printf("This is test  6: |% -3.*u|---|%5s|\n", e, b, "% -3.*u");
	printf("This is test  7: |%+-3.*u|---|%5s|\n", e, b, "%+-3.*u");
	printf("This is test  8: |%0-3.*u|---|%5s|\n", e, b, "%0-3.*u");
	printf("This is test  9: |%0+3.*u|---|%5s|\n", e, b, "%0+3.*u");
	printf("This is test 10: |% 03.*u|---|%5s|\n", e, b, "% 03.*u");
	printf("This is test 11: |% -3.*u|---|%5s|\n\n", e, b, "% -3.*u");

	printf("STANDART TYPE o:\nnumber > 0\n");
	printf("This is test  0: |%3.*o|---|%5s|\n", e, a, "%3.*o");
	printf("This is test  1: |%+3.*o|---|%5s|\n", e, a, "%+3.*o");
	printf("This is test  2: |%-3.*o|---|%5s|\n", e, a, "%-3.*o");
	printf("This is test  3: |% 3.*o|---|%5s|\n", e, a, "% 3.*o");
	printf("This is test  4: |%#3.*o|---|%5s|\n", e, a, "%#3.*o");
	printf("This is test  5: |%03.*o|---|%5s|\n", e, a, "%03.*o");
	printf("This is test  6: |%#+3.*o|---|%5s|\n", e, a, "%#+3.*o");
	printf("This is test  7: |%#-3.*o|---|%5s|\n", e, a, "%#-3.*o");
	printf("This is test  8: |%#03.*o|---|%5s|\n", e, a, "%#03.*o");
	printf("This is test  9: |% #3.*o|---|%5s|\n", e, a, "% #3.*o");
	printf("This is test 10: |%+-3.*o|---|%5s|\n", e, a, "%+-3.*o");
	printf("This is test 11: |%+03.*o|---|%5s|\n", e, a, "%+03.*o");
	printf("This is test 12: |% +3.*o|---|%5s|\n", e, a, "% +3.*o");
	printf("This is test 13: |%-03.*o|---|%5s|\n", e, a, "%-03.*o");
	printf("This is test 14: |% -3.*o|---|%5s|\n", e, a, "% -3.*o");
	printf("This is test 15: |% 03.*o|---|%5s|\n\n", e, a, "% 03.*o");

	printf("number < 0\n");
	printf("This is test  0: |%3.*o|---|%5s|\n", e, b, "%3.*o");
	printf("This is test  1: |%+3.*o|---|%5s|\n", e, b, "%+3.*o");
	printf("This is test  2: |%-3.*o|---|%5s|\n", e, b, "%-3.*o");
	printf("This is test  3: |% 3.*o|---|%5s|\n", e, b, "% 3.*o");
	printf("This is test  4: |%#3.*o|---|%5s|\n", e, b, "%#3.*o");
	printf("This is test  5: |%03.*o|---|%5s|\n", e, b, "%03.*o");
	printf("This is test  6: |%#+3.*o|---|%5s|\n", e, b, "%#+3.*o");
	printf("This is test  7: |%#-3.*o|---|%5s|\n", e, b, "%#-3.*o");
	printf("This is test  8: |%#03.*o|---|%5s|\n", e, b, "%#03.*o");
	printf("This is test  9: |% #3.*o|---|%5s|\n", e, b, "% #3.*o");
	printf("This is test 10: |%+-3.*o|---|%5s|\n", e, b, "%+-3.*o");
	printf("This is test 11: |%+03.*o|---|%5s|\n", e, b, "%+03.*o");
	printf("This is test 12: |% +3.*o|---|%5s|\n", e, b, "% +3.*o");
	printf("This is test 13: |%-03.*o|---|%5s|\n", e, b, "%-03.*o");
	printf("This is test 14: |% -3.*o|---|%5s|\n", e, b, "% -3.*o");
	printf("This is test 15: |% 03.*o|---|%5s|\n\n", e, b, "% 03.*o");

	printf("STANDART TYPE x (X):\nnumber > 0\n");
	printf("This is test  0: |%5.*x|---|%5s|\n", e, a, "%5.*x");
	printf("This is test  1: |%+5.*x|---|%5s|\n", e, a, "%+5.*x");
	printf("This is test  2: |%-5.*x|---|%5s|\n", e, a, "%-5.*x");
	printf("This is test  3: |% 5.*x|---|%5s|\n", e, a, "% 5.*x");
	printf("This is test  4: |%#5.*x|---|%5s|\n", e, a, "%#5.*x");
	printf("This is test  5: |%05.*x|---|%5s|\n", e, a, "%05.*x");
	printf("This is test  6: |%#+5.*x|---|%5s|\n", e, a, "%#+5.*x");
	printf("This is test  7: |%#-5.*x|---|%5s|\n", e, a, "%#-5.*x");
	printf("This is test  8: |%#05.*x|---|%5s|\n", e, a, "%#05.*x");
	printf("This is test  9: |% #5.*x|---|%5s|\n", e, a, "% #5.*x");
	printf("This is test 10: |%+-5.*x|---|%5s|\n", e, a, "%+-5.*x");
	printf("This is test 11: |%+05.*x|---|%5s|\n", e, a, "%+05.*x");
	printf("This is test 12: |% +5.*x|---|%5s|\n", e, a, "% +5.*x");
	printf("This is test 13: |%-05.*x|---|%5s|\n", e, a, "%-05.*x");
	printf("This is test 14: |% -5.*x|---|%5s|\n", e, a, "% -5.*x");
	printf("This is test 15: |% 05.*x|---|%5s|\n\n", e, a, "% 05.*x");

	printf("number < 0\n");
	printf("This is test  0: |%5.*x|---|%5s|\n", e, b, "%5.*x");
	printf("This is test  1: |%+5.*x|---|%5s|\n", e, b, "%+5.*x");
	printf("This is test  2: |%-5.*x|---|%5s|\n", e, b, "%-5.*x");
	printf("This is test  3: |% 5.*x|---|%5s|\n", e, b, "% 5.*x");
	printf("This is test  4: |%#5.*x|---|%5s|\n", e, b, "%#5.*x");
	printf("This is test  5: |%05.*x|---|%5s|\n", e, b, "%05.*x");
	printf("This is test  6: |%#+5.*x|---|%5s|\n", e, b, "%#+5.*x");
	printf("This is test  7: |%#-5.*x|---|%5s|\n", e, b, "%#-5.*x");
	printf("This is test  8: |%#05.*x|---|%5s|\n", e, b, "%#05.*x");
	printf("This is test  9: |% #5.*x|---|%5s|\n", e, b, "% #5.*x");
	printf("This is test 10: |%+-5.*x|---|%5s|\n", e, b, "%+-5.*x");
	printf("This is test 11: |%+05.*x|---|%5s|\n", e, b, "%+05.*x");
	printf("This is test 12: |% +5.*x|---|%5s|\n", e, b, "% +5.*x");
	printf("This is test 13: |%-05.*x|---|%5s|\n", e, b, "%-05.*x");
	printf("This is test 14: |% -5.*x|---|%5s|\n", e, b, "% -5.*x");
	printf("This is test 15: |% 05.*x|---|%5s|\n\n", e, b, "% 05.*x");

	printf("STANDART TYPE c:\n");
	printf("This is test  0: |%5.*c|---|%5s|\n", e, c, "%5.*c");
	printf("This is test  1: |%+5.*c|---|%5s|\n", e, c, "%+5.*c");
	printf("This is test  2: |%-5.*c|---|%5s|\n", e, c, "%-5.*c");
	printf("This is test  3: |% 5.*c|---|%5s|\n", e, c, "% 5.*c");
	printf("This is test  4: |%#5.*c|---|%5s|\n", e, c, "%#5.*c");
	printf("This is test  5: |%05.*c|---|%5s|\n", e, c, "%05.*c");
	printf("This is test  6: |%#+5.*c|---|%5s|\n", e, c, "%#+5.*c");
	printf("This is test  7: |%#-5.*c|---|%5s|\n", e, c, "%#-5.*c");
	printf("This is test  8: |%#05.*c|---|%5s|\n", e, c, "%#05.*c");
	printf("This is test  9: |% #5.*c|---|%5s|\n", e, c, "% #5.*c");
	printf("This is test 10: |%+-5.*c|---|%5s|\n", e, c, "%+-5.*c");
	printf("This is test 11: |%+05.*c|---|%5s|\n", e, c, "%+05.*c");
	printf("This is test 12: |% +5.*c|---|%5s|\n", e, c, "% +5.*c");
	printf("This is test 13: |%-05.*c|---|%5s|\n", e, c, "%-05.*c");
	printf("This is test 14: |% -5.*c|---|%5s|\n", e, c, "% -5.*c");
	printf("This is test 15: |% 05.*c|---|%5s|\n\n", e, c, "% 05.*c");

	printf("STANDART TYPE s:\n");
	printf("This is test  0: |%5.*s|---|%5s|\n", e, str, "%5.*s");
	printf("This is test  1: |%+5.*s|---|%5s|\n", e, str, "%+5.*s");
	printf("This is test  2: |%-5.*s|---|%5s|\n", e, str, "%-5.*s");
	printf("This is test  3: |% 5.*s|---|%5s|\n", e, str, "% 5.*s");
	printf("This is test  4: |%#5.*s|---|%5s|\n", e, str, "%#5.*s");
	printf("This is test  5: |%05.*s|---|%5s|\n", e, str, "%05.*s");
	printf("This is test  6: |%#+5.*s|---|%5s|\n", e, str, "%#+5.*s");
	printf("This is test  7: |%#-5.*s|---|%5s|\n", e, str, "%#-5.*s");
	printf("This is test  8: |%#05.*s|---|%5s|\n", e, str, "%#05.*s");
	printf("This is test  9: |% #5.*s|---|%5s|\n", e, str, "% #5.*s");
	printf("This is test 10: |%+-5.*s|---|%5s|\n", e, str, "%+-5.*s");
	printf("This is test 11: |%+05.*s|---|%5s|\n", e, str, "%+05.*s");
	printf("This is test 12: |% +5.*s|---|%5s|\n", e, str, "% +5.*s");
	printf("This is test 13: |%-05.*s|---|%5s|\n", e, str, "%-05.*s");
	printf("This is test 14: |% -5.*s|---|%5s|\n", e, str, "% -5.*s");
	printf("This is test 15: |% 05.*s|---|%5s|\n", e, str, "% 05.*s");

	int	w = 20;
	int	p[2] = {10, 12};
	//int	p1 = 107;
	//int	*p = &p1;
	e = 25;

	printf("STANDART TYPE p:\n");
	printf("This is test  0: |%*.*p|---|%5s|\n", w, e, p, "%5.*p");
	printf("This is test  1: |%+*.*p|---|%5s|\n", w, e, p, "%+5.*p");
	printf("This is test  2: |%-*.*p|---|%5s|\n", w, e, p, "%-5.*p");
	printf("This is test  3: |% *.*p|---|%5s|\n", w, e, p, "% 5.*p");
	printf("This is test  4: |%#*.*p|---|%5s|\n", w, e, p, "%#5.*p");
	printf("This is test  5: |%0*.*p|---|%5s|\n", w, e, p, "%05.*p");
	printf("This is test  6: |%#+*.*p|---|%5s|\n", w, e, p, "%#+5.*p");
	printf("This is test  7: |%#-*.*p|---|%5s|\n", w, e, p, "%#-5.*p");
	printf("This is test  8: |%#0*.*p|---|%5s|\n", w, e, p, "%#05.*p");
	printf("This is test  9: |% #*.*p|---|%5s|\n", w, e, p, "% #5.*p");
	printf("This is test 10: |%+-*.*p|---|%5s|\n", w, e, p, "%+-5.*p");
	printf("This is test 11: |%+0*.*p|---|%5s|\n", w, e, p, "%+05.*p");
	printf("This is test 12: |% +*.*p|---|%5s|\n", w, e, p, "% +5.*p");
	printf("This is test 13: |%-0*.*p|---|%5s|\n", w, e, p, "%-05.*p");
	printf("This is test 14: |% -*.*p|---|%5s|\n", w, e, p, "% -5.*p");
	printf("This is test 15: |% 0*.*p|---|%5s|\n\n", w, e, p, "% 05.*p");

	printf("STANDART TYPE p:\n");
	printf("This is test  0: |%*p|---|%5s|\n", w, p, "%*p");
	printf("This is test  1: |%+*p|---|%5s|\n", w, p, "%+*p");
	printf("This is test  2: |%-*p|---|%5s|\n", w, p, "%-*p");
	printf("This is test  3: |% *p|---|%5s|\n", w, p, "% *p");
	printf("This is test  4: |%#*p|---|%5s|\n", w, p, "%#*p");
	printf("This is test  5: |%0*p|---|%5s|\n", w, p, "%0*p");
	printf("This is test  6: |%#+*p|---|%5s|\n", w, p, "%#+*p");
	printf("This is test  7: |%#-*p|---|%5s|\n", w, p, "%#-*p");
	printf("This is test  8: |%#0*p|---|%5s|\n", w, p, "%#0*p");
	printf("This is test  9: |% #*p|---|%5s|\n", w, p, "% #*p");
	printf("This is test 10: |%+-*p|---|%5s|\n", w, p, "%+-*p");
	printf("This is test 11: |%+0*p|---|%5s|\n", w, p, "%+0*p");
	printf("This is test 12: |% +*p|---|%5s|\n", w, p, "% +*p");
	printf("This is test 13: |%-0*p|---|%5s|\n", w, p, "%-0*p");
	printf("This is test 14: |% -*p|---|%5s|\n", w, p, "% -*p");
	printf("This is test 15: |% 0*p|---|%5s|\n\n", w, p, "% 0*p");

	printf("STANDART TYPE p:\n");
	printf("This is test  0: |%p|---|%5s|\n", p, "%p");
	printf("This is test  1: |%+p|---|%5s|\n", p, "%+p");
	printf("This is test  2: |%-p|---|%5s|\n", p, "%-p");
	printf("This is test  3: |% p|---|%5s|\n", p, "% p");
	printf("This is test  4: |%#p|---|%5s|\n", p, "%#p");
	printf("This is test  5: |%0p|---|%5s|\n", p, "%0p");
	printf("This is test  6: |%#+p|---|%5s|\n", p, "%#+p");
	printf("This is test  7: |%#-p|---|%5s|\n", p, "%#-p");
	printf("This is test  8: |%#0p|---|%5s|\n", p, "%#0p");
	printf("This is test  9: |% #p|---|%5s|\n", p, "% #p");
	printf("This is test 10: |%+-p|---|%5s|\n", p, "%+-p");
	printf("This is test 11: |%+0p|---|%5s|\n", p, "%+0p");
	printf("This is test 12: |% +p|---|%5s|\n", p, "% +p");
	printf("This is test 13: |%-0p|---|%5s|\n", p, "%-0p");
	printf("This is test 14: |% -p|---|%5s|\n", p, "% -p");
	printf("This is test 15: |% 0p|---|%5s|\n\n", p, "% 0p");

/*
	// printf("-->|");         
	// printf("%-15x", 542);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%5.2x", 5427);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%#llx", 9223372036854775807);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%#x", 0);
	// printf("|<--\n");
	// printf("-->|");      
	// printf("@moulitest: %#.x %#.0x", 0, 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %.x %.0x", 0, 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %5.x %5.0x", 0, 0);
	// printf("|<--\n");

	// printf("-->|");
	// printf("%s", "this is a string");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%s ", "this is a string");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%s  ", "this is a string");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%5.2s is a string", "");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%-10s is a string", "this");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%-5.2s is a string", "");
	// printf("|<--\n");

	// printf("-->|");
	// printf("@moulitest: %s", NULL);     
	// printf("|<--\n");
	// printf("-->|");
	// printf("%.2c", NULL);          
	// printf("|<--\n");
	// printf("-->|");
	// printf("%s %s", NULL, "string");   
	// printf("|<--\n");

/*	printf("-->|");
	printf("@moulitest: %c", 0);
	printf("|<--\n");
	printf("-->|");
	printf("%2c", 0);
	printf("|<--\n");
	printf("-->|");
	printf("null %c and text", 0);
	printf("|<--\n");
	printf("-->|");
	printf("% c", 0);
	printf("|<--\n");
*/
	// printf("-->|");
	// printf("@moulitest: %.o %.0o", 0, 0); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %5.o %5.0o", 0, 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %#.o %#.0o", 0, 0);
	// printf("|<--\n");

	// printf("-->|");
	// printf("%d", 2147483648);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%d", -2147483648);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%+d", 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%ld", -2147483648);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%ld", 2147483648); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%ld", -2147483649);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lld", 9223372036854775807); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lld", -9223372036854775808); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %.d %.0d", 0, 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %5.d %5.0d", 0, 0);
	// printf("|<--\n");

	// printf("-->|");
	// printf("%u", -1);         
	// printf("|<--\n");
	// printf("-->|");
	// printf("%u", 4294967295); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%5u", 4294967295);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%15u", 4294967295); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%-15u", 4294967295); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%015u", 4294967295); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("% u", 4294967295);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%+u", 4294967295);       
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lu", 4294967295);       
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lu", 4294967296);           
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lu", -42);                   
	// printf("|<--\n");
	// printf("-->|");
	// printf("%llu", 4999999999); 
	// printf("|<--\n");

/*	printf("-->|");
	printf("%#llx", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%s ", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%s  ", "this is a string");
	printf("|<--\n");
*/
/*	printf("-->|");
	printf("%");
	printf("|<--\n");
	printf("-->|");
	printf("% ");
	printf("|<--\n");
	printf("-->|");
	printf("% h");
	printf("|<--\n");
	printf("-->|");
	printf("% hZ%");
	printf("|<--\n");
	printf("-->|");
	printf("%jx", 4294967295);
	printf("|<--\n");
	printf("-->|");
	printf("%jx", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%jx", -4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%jx", -4294967297);
	printf("|<--\n");
	printf("-->|");
	printf("%ll#x", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%010s is a string", "this");
	printf("|<--\n");
	printf("-->|");
	printf("%5+d", 42);
	printf("|<--\n");
	printf("-->|");
	printf("%5+d", -42);
	printf("|<--\n");
	printf("-->|");
	printf("%-5+d", 42);
	printf("|<--\n");
	printf("-->|");
	printf("%-5+d", -42);
	printf("|<--\n");
	printf("-->|");
	printf("%jd", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%jd", -9223372036854775808);
	printf("|<--\n");
	printf("-->|");
	printf("%zd", 4294967295);
	printf("|<--\n");
	printf("-->|");
	printf("%zd", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%zd", -0);
	printf("|<--\n");
	printf("-->|");
	printf("%zd", -1);
	printf("|<--\n");
	printf("-->|");
	printf("%ju", 4999999999);
	printf("|<--\n");
	printf("-->|");
	printf("%ju", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%hU", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%U", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%zhd", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%jzd", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%jhd", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%lhl", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%lhlz", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%zj", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%lhh", 2147483647);
	printf("|<--\n");
	printf("-->|");
	printf("%hhld", 128);
	printf("|<--\n");
	printf("-->|");
	printf("@main_ftprintf: %####0000 33..1..#00d\n", 256);
	printf("|<--\n");
	printf("-->|");
	printf("@main_ftprintf: %####0000 33..1d", 256);
	printf("|<--\n");
	printf("-->|");
	printf("@main_ftprintf: %###-#0000 33...12..#0+0d", 256);
	printf("|<--\n");
*/

/*	printf("-->|");
	printf("%s", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%s ", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%s  ", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%5.2s is a string", "");
	printf("|<--\n");
	printf("-->|");
	printf("%-10s is a string", "this");
	printf("|<--\n");
	printf("-->|");
	printf("%-5.2s is a string", "");
	printf("|<--\n");
*/
	return (0);
}