#include <stdio.h>
#include <limits.h>

int	main()
{

// PFT TEST


	printf("-->|");
	printf("%05");
	printf("|<--\n");
	printf("-->|");
	printf("%-5");
	printf("|<--\n");


	// 	printf("-->|");
	// printf("%c", (char)0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%5c", (char)0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%-5c", (char)0);
	// 	printf("|<--\n");



// 		printf("-->|");
// 	printf("Kashim a %c histoires √† raconter", 1001);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("Il fait au moins %c", -8000);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%c", -0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%c", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%c", INT_MAX);
// 		printf("|<--\n");

// printf("\n");

// 		printf("-->|");
// 	printf("%c - \u03B1;", L'\u03B1');
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%c", L'\u03B1');
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%lc", L'\u03B1');
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%C", L'\u03B1');
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%lC", L'\u03B1');
// 		printf("|<--\n");


// ft_c

	// 	printf("-->|");
	// printf("%c", (char)'\x3f');
	// 	printf("|<--\n");


/*		printf("-->|");
	printf("%c", (char)1);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)2);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)3);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)4);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)5);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)6);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)7);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)8);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)9);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)10);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)11);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)12);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)13);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)14);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)15);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)16);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)17);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)18);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)19);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)20);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)21);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)22);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)23);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)24);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)25);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)26);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)27);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)28);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)29);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)30);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)31);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)32);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)33);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)34);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)35);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)36);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)37);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)38);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)39);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)40);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)41);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)42);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)43);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)44);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)45);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)46);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)47);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)48);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)49);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)50);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)51);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)52);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)53);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)54);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)55);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)56);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)57);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)58);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)59);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)60);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)61);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)62);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)63);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)64);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)65);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)66);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)67);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)68);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)69);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)70);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)71);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)72);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)73);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)74);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)75);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)76);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)77);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)78);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)79);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)80);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)81);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)82);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)83);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)84);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)85);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)86);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)87);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)88);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)89);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)90);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)91);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)92);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)93);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)94);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)95);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)96);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)97);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)98);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)99);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)100);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)101);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)102);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)103);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)104);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)105);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)106);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)107);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)108);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)109);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)110);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)111);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)112);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)113);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)114);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)115);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)116);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)117);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)118);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)119);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)120);
		printf("|<--\n");

printf("\n");

		printf("-->|");
	printf("%c", (char)121);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)122);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)123);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)124);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)125);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)126);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)127);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)128);
		printf("|<--\n");
		printf("-->|");
	printf("%c", (char)228);
		printf("|<--\n");


*/









//	ft_d and ft_i

// 		printf("-->|");
// 	printf("%8.3d", 8375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%8.3d", -8473);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+8.3d", 8375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+8.3d", -8473);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%08.3d", 8375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%08.3d", -8473);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%0+8.3d", 8375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%0+8.3d", -8473);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 8.3d", 8375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 8.3d", -8473);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% +8.3d", 8375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% +8.3d", -8473);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 08.3d", 8375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 08.3d", -8473);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 0+8.3d", 8375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 0+8.3d", -8473);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+.0d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+.d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+5.0d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+5.d", 0);
// 		printf("|<--\n");

// printf("\n");


// 		printf("-->|");
// 	printf("%.5d", 2);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%.6d", -3);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%.3d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%.4d", 5263);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%.4d", -2372);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+.7d", 234);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+.7d", -446);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%8.5d", 34);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%10.5d", -216);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%8.5d", 0);
// 		printf("|<--\n");

// printf("\n");

// 		printf("-->|");
// 	printf("%3.7d", 3267);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%3.7d", -2375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+8.5d", 34);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+10.5d", -216);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+8.5d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+3.7d", 3267);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%+3.7d", -2375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%08.5d", 34);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%010.5d", -216);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%08.5d", 0);
// 		printf("|<--\n");
	
// printf("\n");
	
// 		printf("-->|");
// 	printf("%03.7d", 3267);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%03.7d", -2375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%0+8.5d", 34);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%0+10.5d", -216);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%0+8.5d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%0+3.7d", 3267);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%0+3.7d", -2375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("%.37ld", -22337203685477l);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% .5d", 2);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% .6d", -3);
// 		printf("|<--\n");

// printf("\n");

// 		printf("-->|");
// 	printf("% .3d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% .4d", 5263);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% .4d", -2372);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% +.7d", 234);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% +.7d", -446);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 8.5d", 34);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 10.5d", -216);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 8.5d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 3.7d", 3267);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 3.7d", -2375);
// 		printf("|<--\n");
	
// printf("\n");

// 		printf("-->|");
// 	printf("% +8.5d", 34);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% +10.5d", -216);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% +8.5d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% +3.7d", 3267);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% +3.7d", -2375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 08.5d", 34);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 010.5d", -216);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 08.5d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 03.7d", 3267);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 03.7d", -2375);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 0+8.5d", 34);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 0+10.5d", -216);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 0+8.5d", 0);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 0+3.7d", 3267);
// 		printf("|<--\n");
// 		printf("-->|");
// 	printf("% 0+3.7d", -2375);
// 		printf("|<--\n");



//printf("\n");
//	ft_u

/*		printf("-->|");
	printf("%.0u", 0);
		printf("|<--\n");
		printf("-->|");
	printf("%.u", 0);
		printf("|<--\n");
		printf("-->|");
	printf("%5.0u", 0);
		printf("|<--\n");
		printf("-->|");
	printf("%5.u", 0);
		printf("|<--\n");
		printf("-->|");
	printf("%-5.0u", 0);
		printf("|<--\n");
		printf("-->|");
	printf("%-5.u", 0);
		printf("|<--\n");
*/



// printf("\n");
//	ft_o

	// 	printf("-->|");
	// printf("this %#o number", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#3o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#-3o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#.0o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#.o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#5.0o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#5.o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#-5.0o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#-5.o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%.0o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%.o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%5.0o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%5.o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%-5.0o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%-5.o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#.3o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#8.5o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#-8.5o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#08.5o", 0);
	// 	printf("|<--\n");
	// 	printf("-->|");
	// printf("%#0-8.5o", 0);
	// 	printf("|<--\n");


//printf("\n");
//	ft_X

/*		printf("-->|");
	printf("%8.5X", 34);
		printf("|<--\n");
		printf("-->|");
	printf("%8.5X", 0);
		printf("|<--\n");
		printf("-->|");
	printf("%08.5X", 34);
		printf("|<--\n");
		printf("-->|");
	printf("%08.5X", 0);
		printf("|<--\n");
		printf("-->|");
	printf("%#8.5X", 0);
		printf("|<--\n");
		printf("-->|");
	printf("%#08.5X", 0);
		printf("|<--\n");

		printf("-->|");
	printf("%#8.5x", 34);
		printf("|<--\n");
		printf("-->|");
	printf("%#08.5x", 34);
		printf("|<--\n");
*/

//	ft_c WHAT?!

//printf("\n");	
//	ft_s

/*		printf("-->|");
	printf("%7.5s", "yolo");
		printf("|<--\n");
		printf("-->|");
	printf("%-7.5s", "yolo");
		printf("|<--\n");
		printf("-->|");
	printf("%3.3s%7.7s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%3.3s%3.7s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%7.7s%3.3s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%3.7s%3.3s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%3.3s%7.3s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%7.3s%3.3s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%3.3s%3.3s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%-10.8s", "hi low");
		printf("|<--\n");
		printf("-->|");
	printf("%-10.8s", NULL);
		printf("|<--\n");
		printf("-->|");
	printf("%.7s", "hello");
		printf("|<--\n");
		printf("-->|");
	printf("%.2s%.7s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%.7s%.2s", "hello", "world");
		printf("|<--\n");
		printf("-->|");
	printf("%.5s%7s", "yo", "boi");
		printf("|<--\n");
		printf("-->|");
	printf("%.9s", "NULL");
		printf("|<--\n");
		printf("-->|");
	printf("%.9s", "hi low");
		printf("|<--\n");
		printf("-->|");
	printf("%.09s", "hi low");
		printf("|<--\n");
		printf("-->|");
	printf("%.09s", NULL);
		printf("|<--\n");
		printf("-->|");
	printf("%-.09s", "hi low");
		printf("|<--\n");
*/


/*		printf("-->|");
	printf("%s", L"text∆");				//s
		printf("|<--\n");
		printf("-->|");
	printf("%S", L"text∆");				//S
		printf("|<--\n");
		printf("-->|");
	printf("%s", "text∆");				//7
		printf("|<--\n");
		printf("-->|");
	printf("%S", "text∆");				//7
		printf("|<--\n");


		printf("-->|");
	printf("%03.2d", 0);
		printf("|<--\n");


	int		a, b, e;
	char	c;
	char	*str = "string";

	a = 12;
	b = -3;
	c = 'M';
	e = 13;

//	printf("This is printf  0: |%#x|---|%5s|\n", 42, "%x");
//	printf("This is printf  2: |%#X|---|%5s|\n", 42, "%X");

	printf("STANDART TYPE d (i):\nnumber > 0\n");
	printf("This is printf  0: |%3.*d|---|%5s|\n", e, a, "%3.*d");
	printf("This is printf  1: |%+3.*d|---|%5s|\n", e, a, "%+3.*d");
	printf("This is printf  2: |%-3.*d|---|%5s|\n", e, a, "%-3.*d");
	printf("This is printf  3: |% 3.*d|---|%5s|\n", e, a, "% 3.*d");
	printf("This is printf  4: |%03.*d|---|%5s|\n", e, a, "%03.*d");
	printf("This is printf  5: |% +3.*d|---|%5s|\n", e, a, "% +3.*d");
	printf("This is printf  6: |% -3.*d|---|%5s|\n", e, a, "% -3.*d");
	printf("This is printf  7: |%+-3.*d|---|%5s|\n", e, a, "%+-3.*d");
	printf("This is printf  8: |%0-3.*d|---|%5s|\n", e, a, "%0-3.*d");
	printf("This is printf  9: |%0+3.*d|---|%5s|\n", e, a, "%0+3.*d");
	printf("This is printf 10: |% 03.*d|---|%5s|\n", e, a, "% 03.*d");
	printf("This is printf 11: |% -3.*d|---|%5s|\n\n", e, a, "% -3.*d");

	printf("number < 0\n");
	printf("This is printf  0: |%3.*d|---|%5s|\n", e, b, "%3.*d");
	printf("This is printf  1: |%+3.*d|---|%5s|\n", e, b, "%+3.*d");
	printf("This is printf  2: |%-3.*d|---|%5s|\n", e, b, "%-3.*d");
	printf("This is printf  3: |% 3.*d|---|%5s|\n", e, b, "% 3.*d");
	printf("This is printf  4: |%03.*d|---|%5s|\n", e, b, "%03.*d");
	printf("This is printf  5: |% +3.*d|---|%5s|\n", e, b, "% +3.*d");
	printf("This is printf  6: |% -3.*d|---|%5s|\n", e, b, "% -3.*d");
	printf("This is printf  7: |%+-3.*d|---|%5s|\n", e, b, "%+-3.*d");
	printf("This is printf  8: |%0-3.*d|---|%5s|\n", e, b, "%0-3.*d");
	printf("This is printf  9: |%0+3.*d|---|%5s|\n", e, b, "%0+3.*d");
	printf("This is printf 10: |% 03.*d|---|%5s|\n", e, b, "% 03.*d");
	printf("This is printf 11: |% -3.*d|---|%5s|\n\n", e, b, "% -3.*d");

	printf("STANDART TYPE u:\nnumber > 0\n");
	printf("This is printf  0: |%3.*u|---|%5s|\n", e, a, "%3.*u");
	printf("This is printf  1: |%+3.*u|---|%5s|\n", e, a, "%+3.*u");
	printf("This is printf  2: |%-3.*u|---|%5s|\n", e, a, "%-3.*u");
	printf("This is printf  3: |% 3.*u|---|%5s|\n", e, a, "% 3.*u");
	printf("This is printf  4: |%03.*u|---|%5s|\n", e, a, "%03.*u");
	printf("This is printf  5: |% +3.*u|---|%5s|\n", e, a, "% +3.*u");
	printf("This is printf  6: |% -3.*u|---|%5s|\n", e, a, "% -3.*u");
	printf("This is printf  7: |%+-3.*u|---|%5s|\n", e, a, "%+-3.*u");
	printf("This is printf  8: |%0-3.*u|---|%5s|\n", e, a, "%0-3.*u");
	printf("This is printf  9: |%0+3.*u|---|%5s|\n", e, a, "%0+3.*u");
	printf("This is printf 10: |% 03.*u|---|%5s|\n", e, a, "% 03.*u");
	printf("This is printf 11: |% -3.*u|---|%5s|\n\n", e, a, "% -3.*u");

	printf("number < 0\n");
	printf("This is printf  1: |%3.*u|---|%5s|\n", e, b, "%3.*u");
	printf("This is printf  1: |%+3.*u|---|%5s|\n", e, b, "%+3.*u");
	printf("This is printf  2: |%-3.*u|---|%5s|\n", e, b, "%-3.*u");
	printf("This is printf  3: |% 3.*u|---|%5s|\n", e, b, "% 3.*u");
	printf("This is printf  4: |%03.*u|---|%5s|\n", e, b, "%03.*u");
	printf("This is printf  5: |% +3.*u|---|%5s|\n", e, b, "% +3.*u");
	printf("This is printf  6: |% -3.*u|---|%5s|\n", e, b, "% -3.*u");
	printf("This is printf  7: |%+-3.*u|---|%5s|\n", e, b, "%+-3.*u");
	printf("This is printf  8: |%0-3.*u|---|%5s|\n", e, b, "%0-3.*u");
	printf("This is printf  9: |%0+3.*u|---|%5s|\n", e, b, "%0+3.*u");
	printf("This is printf 10: |% 03.*u|---|%5s|\n", e, b, "% 03.*u");
	printf("This is printf 11: |% -3.*u|---|%5s|\n\n", e, b, "% -3.*u");

	printf("STANDART TYPE o:\nnumber > 0\n");
	printf("This is printf  0: |%3.*o|---|%5s|\n", e, a, "%3.*o");
	printf("This is printf  1: |%+3.*o|---|%5s|\n", e, a, "%+3.*o");
	printf("This is printf  2: |%-3.*o|---|%5s|\n", e, a, "%-3.*o");
	printf("This is printf  3: |% 3.*o|---|%5s|\n", e, a, "% 3.*o");
	printf("This is printf  4: |%#3.*o|---|%5s|\n", e, a, "%#3.*o");
	printf("This is printf  5: |%03.*o|---|%5s|\n", e, a, "%03.*o");
	printf("This is printf  6: |%#+3.*o|---|%5s|\n", e, a, "%#+3.*o");
	printf("This is printf  7: |%#-3.*o|---|%5s|\n", e, a, "%#-3.*o");
	printf("This is printf  8: |%#03.*o|---|%5s|\n", e, a, "%#03.*o");
	printf("This is printf  9: |% #3.*o|---|%5s|\n", e, a, "% #3.*o");
	printf("This is printf 10: |%+-3.*o|---|%5s|\n", e, a, "%+-3.*o");
	printf("This is printf 11: |%+03.*o|---|%5s|\n", e, a, "%+03.*o");
	printf("This is printf 12: |% +3.*o|---|%5s|\n", e, a, "% +3.*o");
	printf("This is printf 13: |%-03.*o|---|%5s|\n", e, a, "%-03.*o");
	printf("This is printf 14: |% -3.*o|---|%5s|\n", e, a, "% -3.*o");
	printf("This is printf 15: |% 03.*o|---|%5s|\n\n", e, a, "% 03.*o");

	printf("number < 0\n");
	printf("This is printf  0: |%3.*o|---|%5s|\n", e, b, "%3.*o");
	printf("This is printf  1: |%+3.*o|---|%5s|\n", e, b, "%+3.*o");
	printf("This is printf  2: |%-3.*o|---|%5s|\n", e, b, "%-3.*o");
	printf("This is printf  3: |% 3.*o|---|%5s|\n", e, b, "% 3.*o");
	printf("This is printf  4: |%#3.*o|---|%5s|\n", e, b, "%#3.*o");
	printf("This is printf  5: |%03.*o|---|%5s|\n", e, b, "%03.*o");
	printf("This is printf  6: |%#+3.*o|---|%5s|\n", e, b, "%#+3.*o");
	printf("This is printf  7: |%#-3.*o|---|%5s|\n", e, b, "%#-3.*o");
	printf("This is printf  8: |%#03.*o|---|%5s|\n", e, b, "%#03.*o");
	printf("This is printf  9: |% #3.*o|---|%5s|\n", e, b, "% #3.*o");
	printf("This is printf 10: |%+-3.*o|---|%5s|\n", e, b, "%+-3.*o");
	printf("This is printf 11: |%+03.*o|---|%5s|\n", e, b, "%+03.*o");
	printf("This is printf 12: |% +3.*o|---|%5s|\n", e, b, "% +3.*o");
	printf("This is printf 13: |%-03.*o|---|%5s|\n", e, b, "%-03.*o");
	printf("This is printf 14: |% -3.*o|---|%5s|\n", e, b, "% -3.*o");
	printf("This is printf 15: |% 03.*o|---|%5s|\n\n", e, b, "% 03.*o");

	printf("STANDART TYPE x (X):\nnumber > 0\n");
	printf("This is printf  0: |%5.*x|---|%5s|\n", e, a, "%5.*x");
	printf("This is printf  1: |%+5.*x|---|%5s|\n", e, a, "%+5.*x");
	printf("This is printf  2: |%-5.*x|---|%5s|\n", e, a, "%-5.*x");
	printf("This is printf  3: |% 5.*x|---|%5s|\n", e, a, "% 5.*x");
	printf("This is printf  4: |%#5.*x|---|%5s|\n", e, a, "%#5.*x");
	printf("This is printf  5: |%05.*x|---|%5s|\n", e, a, "%05.*x");
	printf("This is printf  6: |%#+5.*x|---|%5s|\n", e, a, "%#+5.*x");
	printf("This is printf  7: |%#-5.*x|---|%5s|\n", e, a, "%#-5.*x");
	printf("This is printf  8: |%#05.*x|---|%5s|\n", e, a, "%#05.*x");
	printf("This is printf  9: |% #5.*x|---|%5s|\n", e, a, "% #5.*x");
	printf("This is printf 10: |%+-5.*x|---|%5s|\n", e, a, "%+-5.*x");
	printf("This is printf 11: |%+05.*x|---|%5s|\n", e, a, "%+05.*x");
	printf("This is printf 12: |% +5.*x|---|%5s|\n", e, a, "% +5.*x");
	printf("This is printf 13: |%-05.*x|---|%5s|\n", e, a, "%-05.*x");
	printf("This is printf 14: |% -5.*x|---|%5s|\n", e, a, "% -5.*x");
	printf("This is printf 15: |% 05.*x|---|%5s|\n\n", e, a, "% 05.*x");

	printf("number < 0\n");
	printf("This is printf  0: |%5.*x|---|%5s|\n", e, b, "%5.*x");
	printf("This is printf  1: |%+5.*x|---|%5s|\n", e, b, "%+5.*x");
	printf("This is printf  2: |%-5.*x|---|%5s|\n", e, b, "%-5.*x");
	printf("This is printf  3: |% 5.*x|---|%5s|\n", e, b, "% 5.*x");
	printf("This is printf  4: |%#5.*x|---|%5s|\n", e, b, "%#5.*x");
	printf("This is printf  5: |%05.*x|---|%5s|\n", e, b, "%05.*x");
	printf("This is printf  6: |%#+5.*x|---|%5s|\n", e, b, "%#+5.*x");
	printf("This is printf  7: |%#-5.*x|---|%5s|\n", e, b, "%#-5.*x");
	printf("This is printf  8: |%#05.*x|---|%5s|\n", e, b, "%#05.*x");
	printf("This is printf  9: |% #5.*x|---|%5s|\n", e, b, "% #5.*x");
	printf("This is printf 10: |%+-5.*x|---|%5s|\n", e, b, "%+-5.*x");
	printf("This is printf 11: |%+05.*x|---|%5s|\n", e, b, "%+05.*x");
	printf("This is printf 12: |% +5.*x|---|%5s|\n", e, b, "% +5.*x");
	printf("This is printf 13: |%-05.*x|---|%5s|\n", e, b, "%-05.*x");
	printf("This is printf 14: |% -5.*x|---|%5s|\n", e, b, "% -5.*x");
	printf("This is printf 15: |% 05.*x|---|%5s|\n\n", e, b, "% 05.*x");

	printf("STANDART TYPE c:\n");
	printf("This is printf  0: |%5.*c|---|%5s|\n", e, c, "%5.*c");
	printf("This is printf  1: |%+5.*c|---|%5s|\n", e, c, "%+5.*c");
	printf("This is printf  2: |%-5.*c|---|%5s|\n", e, c, "%-5.*c");
	printf("This is printf  3: |% 5.*c|---|%5s|\n", e, c, "% 5.*c");
	printf("This is printf  4: |%#5.*c|---|%5s|\n", e, c, "%#5.*c");
	printf("This is printf  5: |%05.*c|---|%5s|\n", e, c, "%05.*c");
	printf("This is printf  6: |%#+5.*c|---|%5s|\n", e, c, "%#+5.*c");
	printf("This is printf  7: |%#-5.*c|---|%5s|\n", e, c, "%#-5.*c");
	printf("This is printf  8: |%#05.*c|---|%5s|\n", e, c, "%#05.*c");
	printf("This is printf  9: |% #5.*c|---|%5s|\n", e, c, "% #5.*c");
	printf("This is printf 10: |%+-5.*c|---|%5s|\n", e, c, "%+-5.*c");
	printf("This is printf 11: |%+05.*c|---|%5s|\n", e, c, "%+05.*c");
	printf("This is printf 12: |% +5.*c|---|%5s|\n", e, c, "% +5.*c");
	printf("This is printf 13: |%-05.*c|---|%5s|\n", e, c, "%-05.*c");
	printf("This is printf 14: |% -5.*c|---|%5s|\n", e, c, "% -5.*c");
	printf("This is printf 15: |% 05.*c|---|%5s|\n\n", e, c, "% 05.*c");

	printf("STANDART TYPE s:\n");
	printf("This is printf  0: |%5.*s|---|%5s|\n", e, str, "%5.*s");
	printf("This is printf  1: |%+5.*s|---|%5s|\n", e, str, "%+5.*s");
	printf("This is printf  2: |%-5.*s|---|%5s|\n", e, str, "%-5.*s");
	printf("This is printf  3: |% 5.*s|---|%5s|\n", e, str, "% 5.*s");
	printf("This is printf  4: |%#5.*s|---|%5s|\n", e, str, "%#5.*s");
	printf("This is printf  5: |%05.*s|---|%5s|\n", e, str, "%05.*s");
	printf("This is printf  6: |%#+5.*s|---|%5s|\n", e, str, "%#+5.*s");
	printf("This is printf  7: |%#-5.*s|---|%5s|\n", e, str, "%#-5.*s");
	printf("This is printf  8: |%#05.*s|---|%5s|\n", e, str, "%#05.*s");
	printf("This is printf  9: |% #5.*s|---|%5s|\n", e, str, "% #5.*s");
	printf("This is printf 10: |%+-5.*s|---|%5s|\n", e, str, "%+-5.*s");
	printf("This is printf 11: |%+05.*s|---|%5s|\n", e, str, "%+05.*s");
	printf("This is printf 12: |% +5.*s|---|%5s|\n", e, str, "% +5.*s");
	printf("This is printf 13: |%-05.*s|---|%5s|\n", e, str, "%-05.*s");
	printf("This is printf 14: |% -5.*s|---|%5s|\n", e, str, "% -5.*s");
	printf("This is printf 15: |% 05.*s|---|%5s|\n", e, str, "% 05.*s");

	int	w = 20;
	int	p[2] = {10, 12};
	//int	p1 = 107;
	//int	*p = &p1;
	e = 25;

	printf("STANDART TYPE p:\n");
	printf("This is printf  0: |%*.*p|---|%5s|\n", w, e, p, "%5.*p");
	printf("This is printf  1: |%+*.*p|---|%5s|\n", w, e, p, "%+5.*p");
	printf("This is printf  2: |%-*.*p|---|%5s|\n", w, e, p, "%-5.*p");
	printf("This is printf  3: |% *.*p|---|%5s|\n", w, e, p, "% 5.*p");
	printf("This is printf  4: |%#*.*p|---|%5s|\n", w, e, p, "%#5.*p");
	printf("This is printf  5: |%0*.*p|---|%5s|\n", w, e, p, "%05.*p");
	printf("This is printf  6: |%#+*.*p|---|%5s|\n", w, e, p, "%#+5.*p");
	printf("This is printf  7: |%#-*.*p|---|%5s|\n", w, e, p, "%#-5.*p");
	printf("This is printf  8: |%#0*.*p|---|%5s|\n", w, e, p, "%#05.*p");
	printf("This is printf  9: |% #*.*p|---|%5s|\n", w, e, p, "% #5.*p");
	printf("This is printf 10: |%+-*.*p|---|%5s|\n", w, e, p, "%+-5.*p");
	printf("This is printf 11: |%+0*.*p|---|%5s|\n", w, e, p, "%+05.*p");
	printf("This is printf 12: |% +*.*p|---|%5s|\n", w, e, p, "% +5.*p");
	printf("This is printf 13: |%-0*.*p|---|%5s|\n", w, e, p, "%-05.*p");
	printf("This is printf 14: |% -*.*p|---|%5s|\n", w, e, p, "% -5.*p");
	printf("This is printf 15: |% 0*.*p|---|%5s|\n\n", w, e, p, "% 05.*p");

	printf("STANDART TYPE p:\n");
	printf("This is printf  0: |%*p|---|%5s|\n", w, p, "%*p");
	printf("This is printf  1: |%+*p|---|%5s|\n", w, p, "%+*p");
	printf("This is printf  2: |%-*p|---|%5s|\n", w, p, "%-*p");
	printf("This is printf  3: |% *p|---|%5s|\n", w, p, "% *p");
	printf("This is printf  4: |%#*p|---|%5s|\n", w, p, "%#*p");
	printf("This is printf  5: |%0*p|---|%5s|\n", w, p, "%0*p");
	printf("This is printf  6: |%#+*p|---|%5s|\n", w, p, "%#+*p");
	printf("This is printf  7: |%#-*p|---|%5s|\n", w, p, "%#-*p");
	printf("This is printf  8: |%#0*p|---|%5s|\n", w, p, "%#0*p");
	printf("This is printf  9: |% #*p|---|%5s|\n", w, p, "% #*p");
	printf("This is printf 10: |%+-*p|---|%5s|\n", w, p, "%+-*p");
	printf("This is printf 11: |%+0*p|---|%5s|\n", w, p, "%+0*p");
	printf("This is printf 12: |% +*p|---|%5s|\n", w, p, "% +*p");
	printf("This is printf 13: |%-0*p|---|%5s|\n", w, p, "%-0*p");
	printf("This is printf 14: |% -*p|---|%5s|\n", w, p, "% -*p");
	printf("This is printf 15: |% 0*p|---|%5s|\n\n", w, p, "% 0*p");

	printf("STANDART TYPE p:\n");
	printf("This is printf  0: |%p|---|%5s|\n", p, "%p");
	printf("This is printf  1: |%+p|---|%5s|\n", p, "%+p");
	printf("This is printf  2: |%-p|---|%5s|\n", p, "%-p");
	printf("This is printf  3: |% p|---|%5s|\n", p, "% p");
	printf("This is printf  4: |%#p|---|%5s|\n", p, "%#p");
	printf("This is printf  5: |%0p|---|%5s|\n", p, "%0p");
	printf("This is printf  6: |%#+p|---|%5s|\n", p, "%#+p");
	printf("This is printf  7: |%#-p|---|%5s|\n", p, "%#-p");
	printf("This is printf  8: |%#0p|---|%5s|\n", p, "%#0p");
	printf("This is printf  9: |% #p|---|%5s|\n", p, "% #p");
	printf("This is printf 10: |%+-p|---|%5s|\n", p, "%+-p");
	printf("This is printf 11: |%+0p|---|%5s|\n", p, "%+0p");
	printf("This is printf 12: |% +p|---|%5s|\n", p, "% +p");
	printf("This is printf 13: |%-0p|---|%5s|\n", p, "%-0p");
	printf("This is printf 14: |% -p|---|%5s|\n", p, "% -p");
	printf("This is printf 15: |% 0p|---|%5s|\n\n", p, "% 0p");


	// printf("-->|");         
	// printf("%-15x", 542);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%5.2x", 5427);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%#llx", 9223372036854775807);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%#x", 0);
	// printf("|<--\n");
	// printf("-->|");      
	// printf("@moulitest: %#.x %#.0x", 0, 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %.x %.0x", 0, 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %5.x %5.0x", 0, 0);
	// printf("|<--\n");

	// printf("-->|");
	// printf("%s", "this is a string");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%s ", "this is a string");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%s  ", "this is a string");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%5.2s is a string", "");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%-10s is a string", "this");
	// printf("|<--\n");
	// printf("-->|");
	// printf("%-5.2s is a string", "");
	// printf("|<--\n");

	// printf("-->|");
	// printf("@moulitest: %s", NULL);     
	// printf("|<--\n");
	// printf("-->|");
	// printf("%.2c", NULL);          
	// printf("|<--\n");
	// printf("-->|");
	// printf("%s %s", NULL, "string");   
	// printf("|<--\n");

	printf("-->|");
	printf("@moulitest: %c", 0);
	printf("|<--\n");
	printf("-->|");
	printf("%2c", 0);
	printf("|<--\n");
	printf("-->|");
	printf("null %c and text", 0);
	printf("|<--\n");
	printf("-->|");
	printf("% c", 0);
	printf("|<--\n");

	// printf("-->|");
	// printf("@moulitest: %.o %.0o", 0, 0); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %5.o %5.0o", 0, 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %#.o %#.0o", 0, 0);
	// printf("|<--\n");

	// printf("-->|");
	// printf("%d", 2147483648);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%d", -2147483648);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%+d", 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%ld", -2147483648);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%ld", 2147483648); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%ld", -2147483649);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lld", 9223372036854775807); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lld", -9223372036854775808); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %.d %.0d", 0, 0);
	// printf("|<--\n");
	// printf("-->|");
	// printf("@moulitest: %5.d %5.0d", 0, 0);
	// printf("|<--\n");

	// printf("-->|");
	// printf("%u", -1);         
	// printf("|<--\n");
	// printf("-->|");
	// printf("%u", 4294967295); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%5u", 4294967295);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%15u", 4294967295); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%-15u", 4294967295); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("%015u", 4294967295); 
	// printf("|<--\n");
	// printf("-->|");
	// printf("% u", 4294967295);
	// printf("|<--\n");
	// printf("-->|");
	// printf("%+u", 4294967295);       
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lu", 4294967295);       
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lu", 4294967296);           
	// printf("|<--\n");
	// printf("-->|");
	// printf("%lu", -42);                   
	// printf("|<--\n");
	// printf("-->|");
	// printf("%llu", 4999999999); 
	// printf("|<--\n");

	printf("-->|");
	printf("%#llx", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%s ", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%s  ", "this is a string");
	printf("|<--\n");

	printf("-->|");
	printf("%");
	printf("|<--\n");
	printf("-->|");
	printf("% ");
	printf("|<--\n");
	printf("-->|");
	printf("% h");
	printf("|<--\n");
	printf("-->|");
	printf("% hZ%");
	printf("|<--\n");
	printf("-->|");
	printf("%jx", 4294967295);
	printf("|<--\n");
	printf("-->|");
	printf("%jx", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%jx", -4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%jx", -4294967297);
	printf("|<--\n");
	printf("-->|");
	printf("%ll#x", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%010s is a string", "this");
	printf("|<--\n");
	printf("-->|");
	printf("%5+d", 42);
	printf("|<--\n");
	printf("-->|");
	printf("%5+d", -42);
	printf("|<--\n");
	printf("-->|");
	printf("%-5+d", 42);
	printf("|<--\n");
	printf("-->|");
	printf("%-5+d", -42);
	printf("|<--\n");
	printf("-->|");
	printf("%jd", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%jd", -9223372036854775808);
	printf("|<--\n");
	printf("-->|");
	printf("%zd", 4294967295);
	printf("|<--\n");
	printf("-->|");
	printf("%zd", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%zd", -0);
	printf("|<--\n");
	printf("-->|");
	printf("%zd", -1);
	printf("|<--\n");
	printf("-->|");
	printf("%ju", 4999999999);
	printf("|<--\n");
	printf("-->|");
	printf("%ju", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%hU", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%U", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%zhd", 4294967296);
	printf("|<--\n");
	printf("-->|");
	printf("%jzd", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%jhd", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%lhl", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%lhlz", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%zj", 9223372036854775807);
	printf("|<--\n");
	printf("-->|");
	printf("%lhh", 2147483647);
	printf("|<--\n");
	printf("-->|");
	printf("%hhld", 128);
	printf("|<--\n");
	printf("-->|");
	printf("@main_ftprintf: %####0000 33..1..#00d\n", 256);
	printf("|<--\n");
	printf("-->|");
	printf("@main_ftprintf: %####0000 33..1d", 256);
	printf("|<--\n");
	printf("-->|");
	printf("@main_ftprintf: %###-#0000 33...12..#0+0d", 256);
	printf("|<--\n");


	printf("-->|");
	printf("%s", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%s ", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%s  ", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%5.2s is a string", "");
	printf("|<--\n");
	printf("-->|");
	printf("%-10s is a string", "this");
	printf("|<--\n");
	printf("-->|");
	printf("%-5.2s is a string", "");
	printf("|<--\n");
*/
	return (0);
}