#include <stdio.h>

int	main()
{
	int		a, b, e;
	char	c;
	char	*str = "string";

	a = 12;
	b = -3;
	c = 'M';
	e = 2;

//	printf("This is test  0: |%#x|---|%5s|\n", 42, "%x");
//	printf("This is test  2: |%#X|---|%5s|\n", 42, "%X");

/*	printf("STANDART TYPE d (i):\nnumber > 0\n");
	printf("This is test  0: |%3.*d|---|%5s|\n", e, a, "%3.*d");
	printf("This is test  1: |%+3.*d|---|%5s|\n", e, a, "%+3.*d");
	printf("This is test  2: |%-3.*d|---|%5s|\n", e, a, "%-3.*d");
	printf("This is test  3: |% 3.*d|---|%5s|\n", e, a, "% 3.*d");
	printf("This is test  4: |%03.*d|---|%5s|\n", e, a, "%03.*d");
	printf("This is test  5: |% +3.*d|---|%5s|\n", e, a, "% +3.*d");
	printf("This is test  6: |% -3.*d|---|%5s|\n", e, a, "% -3.*d");
	printf("This is test  7: |%+-3.*d|---|%5s|\n", e, a, "%+-3.*d");
	printf("This is test  8: |%0-3.*d|---|%5s|\n", e, a, "%0-3.*d");
	printf("This is test  9: |%0+3.*d|---|%5s|\n", e, a, "%0+3.*d");
	printf("This is test 10: |% 03.*d|---|%5s|\n", e, a, "% 03.*d");
	printf("This is test 11: |% -3.*d|---|%5s|\n\n", e, a, "% -3.*d");

	printf("number < 0\n");
	printf("This is test  0: |%3.*d|---|%5s|\n", e, b, "%3.*d");
	printf("This is test  1: |%+3.*d|---|%5s|\n", e, b, "%+3.*d");
	printf("This is test  2: |%-3.*d|---|%5s|\n", e, b, "%-3.*d");
	printf("This is test  3: |% 3.*d|---|%5s|\n", e, b, "% 3.*d");
	printf("This is test  4: |%03.*d|---|%5s|\n", e, b, "%03.*d");
	printf("This is test  5: |% +3.*d|---|%5s|\n", e, b, "% +3.*d");
	printf("This is test  6: |% -3.*d|---|%5s|\n", e, b, "% -3.*d");
	printf("This is test  7: |%+-3.*d|---|%5s|\n", e, b, "%+-3.*d");
	printf("This is test  8: |%0-3.*d|---|%5s|\n", e, b, "%0-3.*d");
	printf("This is test  9: |%0+3.*d|---|%5s|\n", e, b, "%0+3.*d");
	printf("This is test 10: |% 03.*d|---|%5s|\n", e, b, "% 03.*d");
	printf("This is test 11: |% -3.*d|---|%5s|\n\n", e, b, "% -3.*d");

	printf("STANDART TYPE u:\nnumber > 0\n");
	printf("This is test  0: |%3.*u|---|%5s|\n", e, a, "%3.*u");
	printf("This is test  1: |%+3.*u|---|%5s|\n", e, a, "%+3.*u");
	printf("This is test  2: |%-3.*u|---|%5s|\n", e, a, "%-3.*u");
	printf("This is test  3: |% 3.*u|---|%5s|\n", e, a, "% 3.*u");
	printf("This is test  4: |%03.*u|---|%5s|\n", e, a, "%03.*u");
	printf("This is test  5: |% +3.*u|---|%5s|\n", e, a, "% +3.*u");
	printf("This is test  6: |% -3.*u|---|%5s|\n", e, a, "% -3.*u");
	printf("This is test  7: |%+-3.*u|---|%5s|\n", e, a, "%+-3.*u");
	printf("This is test  8: |%0-3.*u|---|%5s|\n", e, a, "%0-3.*u");
	printf("This is test  9: |%0+3.*u|---|%5s|\n", e, a, "%0+3.*u");
	printf("This is test 10: |% 03.*u|---|%5s|\n", e, a, "% 03.*u");
	printf("This is test 11: |% -3.*u|---|%5s|\n\n", e, a, "% -3.*u");

	printf("number < 0\n");
	printf("This is test  1: |%3.*u|---|%5s|\n", e, b, "%3.*u");
	printf("This is test  1: |%+3.*u|---|%5s|\n", e, b, "%+3.*u");
	printf("This is test  2: |%-3.*u|---|%5s|\n", e, b, "%-3.*u");
	printf("This is test  3: |% 3.*u|---|%5s|\n", e, b, "% 3.*u");
	printf("This is test  4: |%03.*u|---|%5s|\n", e, b, "%03.*u");
	printf("This is test  5: |% +3.*u|---|%5s|\n", e, b, "% +3.*u");
	printf("This is test  6: |% -3.*u|---|%5s|\n", e, b, "% -3.*u");
	printf("This is test  7: |%+-3.*u|---|%5s|\n", e, b, "%+-3.*u");
	printf("This is test  8: |%0-3.*u|---|%5s|\n", e, b, "%0-3.*u");
	printf("This is test  9: |%0+3.*u|---|%5s|\n", e, b, "%0+3.*u");
	printf("This is test 10: |% 03.*u|---|%5s|\n", e, b, "% 03.*u");
	printf("This is test 11: |% -3.*u|---|%5s|\n\n", e, b, "% -3.*u");

	printf("STANDART TYPE o:\nnumber > 0\n");
	printf("This is test  0: |%3.*o|---|%5s|\n", e, a, "%3.*o");
	printf("This is test  1: |%+3.*o|---|%5s|\n", e, a, "%+3.*o");
	printf("This is test  2: |%-3.*o|---|%5s|\n", e, a, "%-3.*o");
	printf("This is test  3: |% 3.*o|---|%5s|\n", e, a, "% 3.*o");
	printf("This is test  4: |%#3.*o|---|%5s|\n", e, a, "%#3.*o");
	printf("This is test  5: |%03.*o|---|%5s|\n", e, a, "%03.*o");
	printf("This is test  6: |%#+3.*o|---|%5s|\n", e, a, "%#+3.*o");
	printf("This is test  7: |%#-3.*o|---|%5s|\n", e, a, "%#-3.*o");
	printf("This is test  8: |%#03.*o|---|%5s|\n", e, a, "%#03.*o");
	printf("This is test  9: |% #3.*o|---|%5s|\n", e, a, "% #3.*o");
	printf("This is test 10: |%+-3.*o|---|%5s|\n", e, a, "%+-3.*o");
	printf("This is test 11: |%+03.*o|---|%5s|\n", e, a, "%+03.*o");
	printf("This is test 12: |% +3.*o|---|%5s|\n", e, a, "% +3.*o");
	printf("This is test 13: |%-03.*o|---|%5s|\n", e, a, "%-03.*o");
	printf("This is test 14: |% -3.*o|---|%5s|\n", e, a, "% -3.*o");
	printf("This is test 15: |% 03.*o|---|%5s|\n\n", e, a, "% 03.*o");

	printf("number < 0\n");
	printf("This is test  0: |%3.*o|---|%5s|\n", e, b, "%3.*o");
	printf("This is test  1: |%+3.*o|---|%5s|\n", e, b, "%+3.*o");
	printf("This is test  2: |%-3.*o|---|%5s|\n", e, b, "%-3.*o");
	printf("This is test  3: |% 3.*o|---|%5s|\n", e, b, "% 3.*o");
	printf("This is test  4: |%#3.*o|---|%5s|\n", e, b, "%#3.*o");
	printf("This is test  5: |%03.*o|---|%5s|\n", e, b, "%03.*o");
	printf("This is test  6: |%#+3.*o|---|%5s|\n", e, b, "%#+3.*o");
	printf("This is test  7: |%#-3.*o|---|%5s|\n", e, b, "%#-3.*o");
	printf("This is test  8: |%#03.*o|---|%5s|\n", e, b, "%#03.*o");
	printf("This is test  9: |% #3.*o|---|%5s|\n", e, b, "% #3.*o");
	printf("This is test 10: |%+-3.*o|---|%5s|\n", e, b, "%+-3.*o");
	printf("This is test 11: |%+03.*o|---|%5s|\n", e, b, "%+03.*o");
	printf("This is test 12: |% +3.*o|---|%5s|\n", e, b, "% +3.*o");
	printf("This is test 13: |%-03.*o|---|%5s|\n", e, b, "%-03.*o");
	printf("This is test 14: |% -3.*o|---|%5s|\n", e, b, "% -3.*o");
	printf("This is test 15: |% 03.*o|---|%5s|\n\n", e, b, "% 03.*o");

	printf("STANDART TYPE x (X):\nnumber > 0\n");
	printf("This is test  0: |%5.*x|---|%5s|\n", e, a, "%5.*x");
	printf("This is test  1: |%+5.*x|---|%5s|\n", e, a, "%+5.*x");
	printf("This is test  2: |%-5.*x|---|%5s|\n", e, a, "%-5.*x");
	printf("This is test  3: |% 5.*x|---|%5s|\n", e, a, "% 5.*x");
	printf("This is test  4: |%#5.*x|---|%5s|\n", e, a, "%#5.*x");
	printf("This is test  5: |%05.*x|---|%5s|\n", e, a, "%05.*x");
	printf("This is test  6: |%#+5.*x|---|%5s|\n", e, a, "%#+5.*x");
	printf("This is test  7: |%#-5.*x|---|%5s|\n", e, a, "%#-5.*x");
	printf("This is test  8: |%#05.*x|---|%5s|\n", e, a, "%#05.*x");
	printf("This is test  9: |% #5.*x|---|%5s|\n", e, a, "% #5.*x");
	printf("This is test 10: |%+-5.*x|---|%5s|\n", e, a, "%+-5.*x");
	printf("This is test 11: |%+05.*x|---|%5s|\n", e, a, "%+05.*x");
	printf("This is test 12: |% +5.*x|---|%5s|\n", e, a, "% +5.*x");
	printf("This is test 13: |%-05.*x|---|%5s|\n", e, a, "%-05.*x");
	printf("This is test 14: |% -5.*x|---|%5s|\n", e, a, "% -5.*x");
	printf("This is test 15: |% 05.*x|---|%5s|\n\n", e, a, "% 05.*x");

	printf("number < 0\n");
	printf("This is test  0: |%5.*x|---|%5s|\n", e, b, "%5.*x");
	printf("This is test  1: |%+5.*x|---|%5s|\n", e, b, "%+5.*x");
	printf("This is test  2: |%-5.*x|---|%5s|\n", e, b, "%-5.*x");
	printf("This is test  3: |% 5.*x|---|%5s|\n", e, b, "% 5.*x");
	printf("This is test  4: |%#5.*x|---|%5s|\n", e, b, "%#5.*x");
	printf("This is test  5: |%05.*x|---|%5s|\n", e, b, "%05.*x");
	printf("This is test  6: |%#+5.*x|---|%5s|\n", e, b, "%#+5.*x");
	printf("This is test  7: |%#-5.*x|---|%5s|\n", e, b, "%#-5.*x");
	printf("This is test  8: |%#05.*x|---|%5s|\n", e, b, "%#05.*x");
	printf("This is test  9: |% #5.*x|---|%5s|\n", e, b, "% #5.*x");
	printf("This is test 10: |%+-5.*x|---|%5s|\n", e, b, "%+-5.*x");
	printf("This is test 11: |%+05.*x|---|%5s|\n", e, b, "%+05.*x");
	printf("This is test 12: |% +5.*x|---|%5s|\n", e, b, "% +5.*x");
	printf("This is test 13: |%-05.*x|---|%5s|\n", e, b, "%-05.*x");
	printf("This is test 14: |% -5.*x|---|%5s|\n", e, b, "% -5.*x");
	printf("This is test 15: |% 05.*x|---|%5s|\n\n", e, b, "% 05.*x");

	printf("STANDART TYPE c:\n");
	printf("This is test  0: |%5.*c|---|%5s|\n", e, c, "%5.*c");
	printf("This is test  1: |%+5.*c|---|%5s|\n", e, c, "%+5.*c");
	printf("This is test  2: |%-5.*c|---|%5s|\n", e, c, "%-5.*c");
	printf("This is test  3: |% 5.*c|---|%5s|\n", e, c, "% 5.*c");
	printf("This is test  4: |%#5.*c|---|%5s|\n", e, c, "%#5.*c");
	printf("This is test  5: |%05.*c|---|%5s|\n", e, c, "%05.*c");
	printf("This is test  6: |%#+5.*c|---|%5s|\n", e, c, "%#+5.*c");
	printf("This is test  7: |%#-5.*c|---|%5s|\n", e, c, "%#-5.*c");
	printf("This is test  8: |%#05.*c|---|%5s|\n", e, c, "%#05.*c");
	printf("This is test  9: |% #5.*c|---|%5s|\n", e, c, "% #5.*c");
	printf("This is test 10: |%+-5.*c|---|%5s|\n", e, c, "%+-5.*c");
	printf("This is test 11: |%+05.*c|---|%5s|\n", e, c, "%+05.*c");
	printf("This is test 12: |% +5.*c|---|%5s|\n", e, c, "% +5.*c");
	printf("This is test 13: |%-05.*c|---|%5s|\n", e, c, "%-05.*c");
	printf("This is test 14: |% -5.*c|---|%5s|\n", e, c, "% -5.*c");
	printf("This is test 15: |% 05.*c|---|%5s|\n\n", e, c, "% 05.*c");

	printf("STANDART TYPE s:\n");
	printf("This is test  0: |%5.*s|---|%5s|\n", e, str, "%5.*s");
	printf("This is test  1: |%+5.*s|---|%5s|\n", e, str, "%+5.*s");
	printf("This is test  2: |%-5.*s|---|%5s|\n", e, str, "%-5.*s");
	printf("This is test  3: |% 5.*s|---|%5s|\n", e, str, "% 5.*s");
	printf("This is test  4: |%#5.*s|---|%5s|\n", e, str, "%#5.*s");
	printf("This is test  5: |%05.*s|---|%5s|\n", e, str, "%05.*s");
	printf("This is test  6: |%#+5.*s|---|%5s|\n", e, str, "%#+5.*s");
	printf("This is test  7: |%#-5.*s|---|%5s|\n", e, str, "%#-5.*s");
	printf("This is test  8: |%#05.*s|---|%5s|\n", e, str, "%#05.*s");
	printf("This is test  9: |% #5.*s|---|%5s|\n", e, str, "% #5.*s");
	printf("This is test 10: |%+-5.*s|---|%5s|\n", e, str, "%+-5.*s");
	printf("This is test 11: |%+05.*s|---|%5s|\n", e, str, "%+05.*s");
	printf("This is test 12: |% +5.*s|---|%5s|\n", e, str, "% +5.*s");
	printf("This is test 13: |%-05.*s|---|%5s|\n", e, str, "%-05.*s");
	printf("This is test 14: |% -5.*s|---|%5s|\n", e, str, "% -5.*s");
	printf("This is test 15: |% 05.*s|---|%5s|\n", e, str, "% 05.*s");

	int	w = 10;
	int	p[2] = {10, 12};
	//int	p1 = 107;
	//int	*p = &p1;
	e = 5;

	printf("STANDART TYPE p:\n");
	printf("This is test  0: |%*.*p|---|%5s|\n", w, e, p, "%5.*p");
	printf("This is test  1: |%+*.*p|---|%5s|\n", w, e, p, "%+5.*p");
	printf("This is test  2: |%-*.*p|---|%5s|\n", w, e, p, "%-5.*p");
	printf("This is test  3: |% *.*p|---|%5s|\n", w, e, p, "% 5.*p");
	printf("This is test  4: |%#*.*p|---|%5s|\n", w, e, p, "%#5.*p");
	printf("This is test  5: |%0*.*p|---|%5s|\n", w, e, p, "%05.*p");
	printf("This is test  6: |%#+*.*p|---|%5s|\n", w, e, p, "%#+5.*p");
	printf("This is test  7: |%#-*.*p|---|%5s|\n", w, e, p, "%#-5.*p");
	printf("This is test  8: |%#0*.*p|---|%5s|\n", w, e, p, "%#05.*p");
	printf("This is test  9: |% #*.*p|---|%5s|\n", w, e, p, "% #5.*p");
	printf("This is test 10: |%+-*.*p|---|%5s|\n", w, e, p, "%+-5.*p");
	printf("This is test 11: |%+0*.*p|---|%5s|\n", w, e, p, "%+05.*p");
	printf("This is test 12: |% +*.*p|---|%5s|\n", w, e, p, "% +5.*p");
	printf("This is test 13: |%-0*.*p|---|%5s|\n", w, e, p, "%-05.*p");
	printf("This is test 14: |% -*.*p|---|%5s|\n", w, e, p, "% -5.*p");
	printf("This is test 15: |% 0*.*p|---|%5s|\n\n", w, e, p, "% 05.*p");

	printf("STANDART TYPE p:\n");
	printf("This is test  0: |%*p|---|%5s|\n", w, p, "%*p");
	printf("This is test  1: |%+*p|---|%5s|\n", w, p, "%+*p");
	printf("This is test  2: |%-*p|---|%5s|\n", w, p, "%-*p");
	printf("This is test  3: |% *p|---|%5s|\n", w, p, "% *p");
	printf("This is test  4: |%#*p|---|%5s|\n", w, p, "%#*p");
	printf("This is test  5: |%0*p|---|%5s|\n", w, p, "%0*p");
	printf("This is test  6: |%#+*p|---|%5s|\n", w, p, "%#+*p");
	printf("This is test  7: |%#-*p|---|%5s|\n", w, p, "%#-*p");
	printf("This is test  8: |%#0*p|---|%5s|\n", w, p, "%#0*p");
	printf("This is test  9: |% #*p|---|%5s|\n", w, p, "% #*p");
	printf("This is test 10: |%+-*p|---|%5s|\n", w, p, "%+-*p");
	printf("This is test 11: |%+0*p|---|%5s|\n", w, p, "%+0*p");
	printf("This is test 12: |% +*p|---|%5s|\n", w, p, "% +*p");
	printf("This is test 13: |%-0*p|---|%5s|\n", w, p, "%-0*p");
	printf("This is test 14: |% -*p|---|%5s|\n", w, p, "% -*p");
	printf("This is test 15: |% 0*p|---|%5s|\n\n", w, p, "% 0*p");

	printf("STANDART TYPE p:\n");
	printf("This is test  0: |%p|---|%5s|\n", p, "%p");
	printf("This is test  1: |%+p|---|%5s|\n", p, "%+p");
	printf("This is test  2: |%-p|---|%5s|\n", p, "%-p");
	printf("This is test  3: |% p|---|%5s|\n", p, "% p");
	printf("This is test  4: |%#p|---|%5s|\n", p, "%#p");
	printf("This is test  5: |%0p|---|%5s|\n", p, "%0p");
	printf("This is test  6: |%#+p|---|%5s|\n", p, "%#+p");
	printf("This is test  7: |%#-p|---|%5s|\n", p, "%#-p");
	printf("This is test  8: |%#0p|---|%5s|\n", p, "%#0p");
	printf("This is test  9: |% #p|---|%5s|\n", p, "% #p");
	printf("This is test 10: |%+-p|---|%5s|\n", p, "%+-p");
	printf("This is test 11: |%+0p|---|%5s|\n", p, "%+0p");
	printf("This is test 12: |% +p|---|%5s|\n", p, "% +p");
	printf("This is test 13: |%-0p|---|%5s|\n", p, "%-0p");
	printf("This is test 14: |% -p|---|%5s|\n", p, "% -p");
	printf("This is test 15: |% 0p|---|%5s|\n\n", p, "% 0p");
*/

	// printf("");                             
	// printf(">%5%<\n");    
	// printf(">%-5%<\n");     
	// printf(">%.0%<\n");                         
	// printf(">%   %<\n", "test");                
	// printf(">%-15x<\n", 542);        
	// printf(">%5.2x<\n", 5427);  
	// printf(">%#llx<\n", 9223372036854775807); 
	// printf(">%#x<\n", 0);                       
	// printf(">@moulitest: %#.x %#.0x<\n", 0, 0);
	// printf(">@moulitest: %.x %.0x<\n", 0, 0); 
	// printf(">@moulitest: %5.x %5.0x<\n", 0, 0);
	printf("-->|");
	printf("%s", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%s ", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%s  ", "this is a string");
	printf("|<--\n");
	printf("-->|");
	printf("%5.2s is a string", "");
	printf("|<--\n");
	printf("-->|");
	printf("%-10s is a string", "this");
	printf("|<--\n");
	printf("-->|");
	printf("%-5.2s is a string", "");
	printf("|<--\n");
	// printf(">@moulitest: %s<\n", NULL);     
	// printf(">%.2c<\n", NULL);          
	// printf(">%s %s<\n", NULL, "string");    
	// printf(">@moulitest: %c<\n", 0);    
	// printf(">%2c<\n", 0);          
	// printf(">null %c and text<\n", 0);  
	// printf(">% c<\n", 0);  
	// printf(">@moulitest: %.o %.0o<\n", 0, 0); 
	// printf(">@moulitest: %5.o %5.0o<\n", 0, 0);
	// printf(">@moulitest: %#.o %#.0o<\n", 0, 0);
	// printf(">%d<\n", 2147483648);
	// printf(">%d<\n", -2147483648);
	// printf(">%+d<\n", 0);
	// printf(">%ld<\n", -2147483648);
	// printf(">%ld<\n", 2147483648); 
	// printf(">%ld<\n", -2147483649);
	// printf(">%lld<\n", 9223372036854775807); 
	// printf(">%lld<\n", -9223372036854775808); 
	// printf(">@moulitest: %.d %.0d<\n", 0, 0);
	// printf(">@moulitest: %5.d %5.0dv\n", 0, 0);
	// printf(">%u<\n", -1);         
	// printf(">%u<\n", 4294967295); 
	// printf(">%5u<\n", 4294967295);
	// printf(">%15u<\n", 4294967295); 
	// printf(">%-15u<\n", 4294967295); 
	// printf(">%015u<\n", 4294967295); 
	// printf(">% u<\n", 4294967295);
	// printf(">%+u<\n", 4294967295);       
	// printf(">%lu<\n", 4294967295);       
	// printf(">%lu<\n", 4294967296);           
	// printf(">%lu<\n", -42);                   
	// printf(">%llu<\n", 4999999999); 

	return (0);
}